package Vue;


import controleur.EcoleDAO;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import static java.time.Clock.system;
import java.util.ArrayList;
import javax.swing.*;
import modele.Ecole;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cynth
 */
public class Affichage extends JFrame{

    /**
     * Creates new form Affichage
     */
    private static Ecole ecole = new Ecole();
    public Affichage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        buttonEleves = new javax.swing.JButton();
        buttonEnseignants = new javax.swing.JButton();
        buttonDisciplines = new javax.swing.JButton();
        buttonClasses = new javax.swing.JButton();
        buttonNiveau = new javax.swing.JButton();
        panelDisciplines = new javax.swing.JPanel();
        accueilDisciplines = new javax.swing.JPanel();
        buttonAjoutDiscipline = new javax.swing.JButton();
        reportDisciplines = new javax.swing.JPanel();
        ajouterDiscipline = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        fieldDiscipline = new javax.swing.JTextField();
        buttonValiderDiscipline = new javax.swing.JButton();
        panelNiveau = new javax.swing.JPanel();
        accueilNiveau = new javax.swing.JPanel();
        buttonAjoutNiveau = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        ajouterNiveau = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fieldNiveau = new javax.swing.JTextField();
        buttonValiderNiveau = new javax.swing.JButton();
        panelEleves = new javax.swing.JPanel();
        accueilEleves = new javax.swing.JPanel();
        fieldEleves = new javax.swing.JTextField();
        buttonRechercheEleve = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        buttonAjoutEleve = new javax.swing.JButton();
        scroll3 = new javax.swing.JScrollPane();
        listeEleves = new javax.swing.JTextArea();
        ajouterEleve = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        fieldPrenomEleve = new javax.swing.JTextField();
        fieldNomEleve = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boxClasse = new javax.swing.JComboBox<>();
        buttonValiderEleve = new javax.swing.JButton();
        rechercherEleve = new javax.swing.JPanel();
        scroll4 = new javax.swing.JScrollPane();
        ficheEleve = new javax.swing.JTextArea();
        reportEleves = new javax.swing.JPanel();
        panelClasses = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        accueilClasses = new javax.swing.JPanel();
        buttonAjoutClasse = new javax.swing.JButton();
        ajouterClasse = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        fieldNomClasse = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fieldAnneeScolaire = new javax.swing.JTextField();
        boxNiveau = new javax.swing.JComboBox<>();
        buttonValiderClasse = new javax.swing.JButton();
        panelEnseignants = new javax.swing.JPanel();
        accueilEnseignants = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldEnseignants = new javax.swing.JTextField();
        buttonRechercheEnseignant = new javax.swing.JButton();
        buttonAjoutEnseignant = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        listeEnseignants = new javax.swing.JTextArea();
        reportEnseignants = new javax.swing.JPanel();
        rechercherEnseignant = new javax.swing.JPanel();
        scroll2 = new javax.swing.JScrollPane();
        ficheEnseignant = new javax.swing.JTextArea();
        ajouterEnseignant = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fieldPrenomEnseignant = new javax.swing.JTextField();
        fieldDisciplineEnseignant = new javax.swing.JTextField();
        fieldNomEnseignant = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonValiderEnseignant = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAccueil = new javax.swing.JMenu();
        menuEleves = new javax.swing.JMenu();
        menuEnseignants = new javax.swing.JMenu();
        menuDisciplines = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        panelMenu.setBackground(new java.awt.Color(0, 153, 153));

        buttonEleves.setBackground(new java.awt.Color(255, 51, 51));
        buttonEleves.setText("Elèves");
        buttonEleves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonElevesActionPerformed(evt);
            }
        });

        buttonEnseignants.setBackground(new java.awt.Color(255, 51, 51));
        buttonEnseignants.setText("Enseignants");
        buttonEnseignants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEnseignantsActionPerformed(evt);
            }
        });

        buttonDisciplines.setBackground(new java.awt.Color(255, 51, 51));
        buttonDisciplines.setText("Disciplines");
        buttonDisciplines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisciplinesActionPerformed(evt);
            }
        });

        buttonClasses.setText("Classes");
        buttonClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonClassesActionPerformed(evt);
            }
        });

        buttonNiveau.setText("Niveau");
        buttonNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNiveauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(buttonEleves)
                .addGap(147, 147, 147)
                .addComponent(buttonEnseignants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addComponent(buttonDisciplines)
                .addGap(41, 41, 41))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(buttonClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonNiveau)
                .addGap(171, 171, 171))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEleves)
                    .addComponent(buttonDisciplines)
                    .addComponent(buttonEnseignants))
                .addGap(91, 91, 91)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonClasses)
                    .addComponent(buttonNiveau))
                .addContainerGap(749, Short.MAX_VALUE))
        );

        jPanel1.add(panelMenu, "card5");

        panelDisciplines.setBackground(new java.awt.Color(255, 51, 204));
        panelDisciplines.setLayout(new java.awt.CardLayout());

        accueilDisciplines.setBackground(new java.awt.Color(255, 51, 51));

        buttonAjoutDiscipline.setText("Ajouter une discipline");
        buttonAjoutDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjoutDisciplineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accueilDisciplinesLayout = new javax.swing.GroupLayout(accueilDisciplines);
        accueilDisciplines.setLayout(accueilDisciplinesLayout);
        accueilDisciplinesLayout.setHorizontalGroup(
            accueilDisciplinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilDisciplinesLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(buttonAjoutDiscipline)
                .addContainerGap(688, Short.MAX_VALUE))
        );
        accueilDisciplinesLayout.setVerticalGroup(
            accueilDisciplinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilDisciplinesLayout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(buttonAjoutDiscipline)
                .addContainerGap(660, Short.MAX_VALUE))
        );

        panelDisciplines.add(accueilDisciplines, "card3");

        javax.swing.GroupLayout reportDisciplinesLayout = new javax.swing.GroupLayout(reportDisciplines);
        reportDisciplines.setLayout(reportDisciplinesLayout);
        reportDisciplinesLayout.setHorizontalGroup(
            reportDisciplinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        reportDisciplinesLayout.setVerticalGroup(
            reportDisciplinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );

        panelDisciplines.add(reportDisciplines, "card2");

        ajouterDiscipline.setBackground(new java.awt.Color(255, 51, 51));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel13.setText("Veuillez ajouter la nouvelle discipline");

        jLabel14.setText("Discipline:");

        buttonValiderDiscipline.setText("Valider");
        buttonValiderDiscipline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderDisciplineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterDisciplineLayout = new javax.swing.GroupLayout(ajouterDiscipline);
        ajouterDiscipline.setLayout(ajouterDisciplineLayout);
        ajouterDisciplineLayout.setHorizontalGroup(
            ajouterDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterDisciplineLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterDisciplineLayout.createSequentialGroup()
                .addContainerGap(398, Short.MAX_VALUE)
                .addGroup(ajouterDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterDisciplineLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)
                        .addComponent(fieldDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(245, 245, 245))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterDisciplineLayout.createSequentialGroup()
                        .addComponent(buttonValiderDiscipline)
                        .addGap(295, 295, 295))))
        );
        ajouterDisciplineLayout.setVerticalGroup(
            ajouterDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterDisciplineLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel13)
                .addGap(46, 46, 46)
                .addGroup(ajouterDisciplineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(fieldDiscipline, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonValiderDiscipline)
                .addContainerGap(827, Short.MAX_VALUE))
        );

        panelDisciplines.add(ajouterDiscipline, "card4");

        jPanel1.add(panelDisciplines, "card5");

        panelNiveau.setLayout(new java.awt.CardLayout());

        buttonAjoutNiveau.setText("Ajouter un niveau");
        buttonAjoutNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjoutNiveauActionPerformed(evt);
            }
        });

        jLabel17.setText("Voici la liste des niveaux de l'école");

        javax.swing.GroupLayout accueilNiveauLayout = new javax.swing.GroupLayout(accueilNiveau);
        accueilNiveau.setLayout(accueilNiveauLayout);
        accueilNiveauLayout.setHorizontalGroup(
            accueilNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilNiveauLayout.createSequentialGroup()
                .addGroup(accueilNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accueilNiveauLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(buttonAjoutNiveau))
                    .addGroup(accueilNiveauLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel17)))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        accueilNiveauLayout.setVerticalGroup(
            accueilNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accueilNiveauLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 825, Short.MAX_VALUE)
                .addComponent(buttonAjoutNiveau)
                .addGap(129, 129, 129))
        );

        panelNiveau.add(accueilNiveau, "card3");

        ajouterNiveau.setBackground(new java.awt.Color(102, 255, 102));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setText("Veuillez ajouter un niveau");

        jLabel16.setText("Niveau:");

        buttonValiderNiveau.setText("Valider");
        buttonValiderNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderNiveauActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterNiveauLayout = new javax.swing.GroupLayout(ajouterNiveau);
        ajouterNiveau.setLayout(ajouterNiveauLayout);
        ajouterNiveauLayout.setHorizontalGroup(
            ajouterNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterNiveauLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
            .addGroup(ajouterNiveauLayout.createSequentialGroup()
                .addGroup(ajouterNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajouterNiveauLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel16)
                        .addGap(35, 35, 35)
                        .addComponent(fieldNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ajouterNiveauLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(buttonValiderNiveau)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        ajouterNiveauLayout.setVerticalGroup(
            ajouterNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterNiveauLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ajouterNiveauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(fieldNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonValiderNiveau)
                .addContainerGap(825, Short.MAX_VALUE))
        );

        panelNiveau.add(ajouterNiveau, "card9");

        jPanel1.add(panelNiveau, "card7");

        panelEleves.setBackground(new java.awt.Color(0, 255, 102));
        panelEleves.setLayout(new java.awt.CardLayout());

        accueilEleves.setBackground(new java.awt.Color(0, 255, 204));

        fieldEleves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldElevesActionPerformed(evt);
            }
        });

        buttonRechercheEleve.setText("Valider");
        buttonRechercheEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRechercheEleveActionPerformed(evt);
            }
        });

        jLabel1.setText("Rechercher un élève");

        buttonAjoutEleve.setText("Ajouter un élève");
        buttonAjoutEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjoutEleveActionPerformed(evt);
            }
        });

        listeEleves.setColumns(20);
        listeEleves.setRows(5);
        scroll3.setViewportView(listeEleves);

        javax.swing.GroupLayout accueilElevesLayout = new javax.swing.GroupLayout(accueilEleves);
        accueilEleves.setLayout(accueilElevesLayout);
        accueilElevesLayout.setHorizontalGroup(
            accueilElevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilElevesLayout.createSequentialGroup()
                .addGroup(accueilElevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accueilElevesLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addComponent(fieldEleves, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(buttonRechercheEleve))
                    .addGroup(accueilElevesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(buttonAjoutEleve))
                    .addGroup(accueilElevesLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(scroll3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        accueilElevesLayout.setVerticalGroup(
            accueilElevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilElevesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(accueilElevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEleves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRechercheEleve)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scroll3, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAjoutEleve)
                .addContainerGap(652, Short.MAX_VALUE))
        );

        panelEleves.add(accueilEleves, "card2");

        ajouterEleve.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel4.setText("Veuillez remplir les informations nécéssaires à l'ajout d'un élève");

        fieldPrenomEleve.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        fieldNomEleve.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel5.setText("Nom:");

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel6.setText("Prénom:");

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel7.setText("Classe:");

        boxClasse.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        boxClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxClasseActionPerformed(evt);
            }
        });

        buttonValiderEleve.setText("Valider");
        buttonValiderEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderEleveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterEleveLayout = new javax.swing.GroupLayout(ajouterEleve);
        ajouterEleve.setLayout(ajouterEleveLayout);
        ajouterEleveLayout.setHorizontalGroup(
            ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterEleveLayout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterEleveLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterEleveLayout.createSequentialGroup()
                        .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(43, 43, 43)
                        .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldPrenomEleve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldNomEleve, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(boxClasse, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(298, 298, 298))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterEleveLayout.createSequentialGroup()
                        .addComponent(buttonValiderEleve)
                        .addGap(377, 377, 377))))
        );
        ajouterEleveLayout.setVerticalGroup(
            ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterEleveLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomEleve, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPrenomEleve, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(ajouterEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonValiderEleve)
                .addContainerGap(689, Short.MAX_VALUE))
        );

        panelEleves.add(ajouterEleve, "card6");

        ficheEleve.setColumns(20);
        ficheEleve.setRows(5);
        scroll4.setViewportView(ficheEleve);

        javax.swing.GroupLayout rechercherEleveLayout = new javax.swing.GroupLayout(rechercherEleve);
        rechercherEleve.setLayout(rechercherEleveLayout);
        rechercherEleveLayout.setHorizontalGroup(
            rechercherEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercherEleveLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(scroll4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        rechercherEleveLayout.setVerticalGroup(
            rechercherEleveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercherEleveLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(scroll4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(772, Short.MAX_VALUE))
        );

        panelEleves.add(rechercherEleve, "card5");

        javax.swing.GroupLayout reportElevesLayout = new javax.swing.GroupLayout(reportEleves);
        reportEleves.setLayout(reportElevesLayout);
        reportElevesLayout.setHorizontalGroup(
            reportElevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        reportElevesLayout.setVerticalGroup(
            reportElevesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );

        panelEleves.add(reportEleves, "card5");

        jPanel1.add(panelEleves, "card4");

        panelClasses.setLayout(new java.awt.CardLayout());

        jLabel18.setText("Voici la liste des classes");
        panelClasses.add(jLabel18, "card2");

        buttonAjoutClasse.setText("Ajouter une classe");
        buttonAjoutClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjoutClasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accueilClassesLayout = new javax.swing.GroupLayout(accueilClasses);
        accueilClasses.setLayout(accueilClassesLayout);
        accueilClassesLayout.setHorizontalGroup(
            accueilClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilClassesLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(buttonAjoutClasse)
                .addContainerGap(640, Short.MAX_VALUE))
        );
        accueilClassesLayout.setVerticalGroup(
            accueilClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilClassesLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(buttonAjoutClasse)
                .addContainerGap(677, Short.MAX_VALUE))
        );

        panelClasses.add(accueilClasses, "card4");

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel19.setText("Veuillez ajouter une nouvelle classe");

        jLabel20.setText("Nom:");

        jLabel21.setText("Niveau:");

        jLabel22.setText("Année scolaire:");

        boxNiveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNiveauActionPerformed(evt);
            }
        });

        buttonValiderClasse.setText("Valider");
        buttonValiderClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderClasseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterClasseLayout = new javax.swing.GroupLayout(ajouterClasse);
        ajouterClasse.setLayout(ajouterClasseLayout);
        ajouterClasseLayout.setHorizontalGroup(
            ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterClasseLayout.createSequentialGroup()
                .addGroup(ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ajouterClasseLayout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel19))
                    .addGroup(ajouterClasseLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addGroup(ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(42, 42, 42)
                        .addGroup(ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxNiveau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fieldNomClasse)
                            .addComponent(fieldAnneeScolaire))))
                .addContainerGap(334, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ajouterClasseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonValiderClasse)
                .addGap(386, 386, 386))
        );
        ajouterClasseLayout.setVerticalGroup(
            ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterClasseLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel19)
                .addGap(26, 26, 26)
                .addGroup(ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(boxNiveau, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(ajouterClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAnneeScolaire, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(32, 32, 32)
                .addComponent(buttonValiderClasse)
                .addContainerGap(758, Short.MAX_VALUE))
        );

        panelClasses.add(ajouterClasse, "card5");

        jPanel1.add(panelClasses, "card6");

        panelEnseignants.setBackground(new java.awt.Color(255, 255, 102));
        panelEnseignants.setLayout(new java.awt.CardLayout());

        accueilEnseignants.setBackground(new java.awt.Color(153, 255, 102));

        jLabel3.setText("Rechercher un enseignant");

        buttonRechercheEnseignant.setText("Valider");
        buttonRechercheEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRechercheEnseignantActionPerformed(evt);
            }
        });

        buttonAjoutEnseignant.setText("Ajouter un enseignant");
        buttonAjoutEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAjoutEnseignantActionPerformed(evt);
            }
        });

        listeEnseignants.setColumns(20);
        listeEnseignants.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        listeEnseignants.setRows(5);
        scroll.setViewportView(listeEnseignants);

        javax.swing.GroupLayout accueilEnseignantsLayout = new javax.swing.GroupLayout(accueilEnseignants);
        accueilEnseignants.setLayout(accueilEnseignantsLayout);
        accueilEnseignantsLayout.setHorizontalGroup(
            accueilEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilEnseignantsLayout.createSequentialGroup()
                .addGroup(accueilEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accueilEnseignantsLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(buttonAjoutEnseignant))
                    .addGroup(accueilEnseignantsLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(accueilEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(accueilEnseignantsLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(27, 27, 27)
                                .addComponent(fieldEnseignants, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(buttonRechercheEnseignant)))))
                .addContainerGap(337, Short.MAX_VALUE))
        );
        accueilEnseignantsLayout.setVerticalGroup(
            accueilEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accueilEnseignantsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(accueilEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldEnseignants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRechercheEnseignant))
                .addGap(34, 34, 34)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonAjoutEnseignant)
                .addContainerGap(639, Short.MAX_VALUE))
        );

        panelEnseignants.add(accueilEnseignants, "card3");

        javax.swing.GroupLayout reportEnseignantsLayout = new javax.swing.GroupLayout(reportEnseignants);
        reportEnseignants.setLayout(reportEnseignantsLayout);
        reportEnseignantsLayout.setHorizontalGroup(
            reportEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 867, Short.MAX_VALUE)
        );
        reportEnseignantsLayout.setVerticalGroup(
            reportEnseignantsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );

        panelEnseignants.add(reportEnseignants, "card2");

        ficheEnseignant.setColumns(20);
        ficheEnseignant.setRows(5);
        scroll2.setViewportView(ficheEnseignant);

        javax.swing.GroupLayout rechercherEnseignantLayout = new javax.swing.GroupLayout(rechercherEnseignant);
        rechercherEnseignant.setLayout(rechercherEnseignantLayout);
        rechercherEnseignantLayout.setHorizontalGroup(
            rechercherEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercherEnseignantLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(scroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        rechercherEnseignantLayout.setVerticalGroup(
            rechercherEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rechercherEnseignantLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(scroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(656, Short.MAX_VALUE))
        );

        panelEnseignants.add(rechercherEnseignant, "card5");

        ajouterEnseignant.setBackground(new java.awt.Color(0, 153, 153));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jLabel9.setText("Veuillez remplir les informations nécéssaires à l'ajout d'un enseignant");

        fieldPrenomEnseignant.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        fieldDisciplineEnseignant.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        fieldNomEnseignant.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel8.setText("Nom:");

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel10.setText("Prénom:");

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel11.setText("Discipline:");

        buttonValiderEnseignant.setText("Valider");
        buttonValiderEnseignant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonValiderEnseignantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ajouterEnseignantLayout = new javax.swing.GroupLayout(ajouterEnseignant);
        ajouterEnseignant.setLayout(ajouterEnseignantLayout);
        ajouterEnseignantLayout.setHorizontalGroup(
            ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterEnseignantLayout.createSequentialGroup()
                .addGroup(ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ajouterEnseignantLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(22, 22, 22)
                        .addGroup(ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldPrenomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldDisciplineEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ajouterEnseignantLayout.createSequentialGroup()
                        .addGap(384, 384, 384)
                        .addComponent(buttonValiderEnseignant))
                    .addGroup(ajouterEnseignantLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        ajouterEnseignantLayout.setVerticalGroup(
            ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajouterEnseignantLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22)
                .addGroup(ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPrenomEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(ajouterEnseignantLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDisciplineEnseignant, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addComponent(buttonValiderEnseignant)
                .addContainerGap(705, Short.MAX_VALUE))
        );

        panelEnseignants.add(ajouterEnseignant, "card4");

        jPanel1.add(panelEnseignants, "card3");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 51, 51));

        menuAccueil.setText("Accueil");
        menuAccueil.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuAccueilMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuAccueil);

        menuEleves.setText("Elèves");
        menuEleves.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuElevesMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuEleves);

        menuEnseignants.setText("Enseignants");
        menuEnseignants.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuEnseignantsMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuEnseignants);

        menuDisciplines.setText("Disciplines");
        menuDisciplines.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuDisciplinesMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuDisciplines);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonElevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonElevesActionPerformed
        jPanel1.removeAll();
        panelEleves.removeAll();
        listeEleves.setText("");
        listeEleves.setBorder(null);
        listeEleves.setBackground(new Color(0,0,0,0));
        listeEleves.setEditable(false);
        scroll3.setOpaque(false);
        scroll3.getViewport().setOpaque(false);
        scroll3.setBorder(null);
        scroll3.setViewportBorder(null);
        ArrayList <JButton> boutonSupp = new ArrayList<>() ;
        ArrayList <JButton> boutonPhoto = new ArrayList<>() ;
        int y = 0;
       
        for(int i = 0; i<ecole.getEleves().size(); i++){
            String ancienneListe = listeEleves.getText();
            String nomEleve = ecole.getEleves().get(i).getNom();
            String prenomEleve = ecole.getEleves().get(i).getPrenom();         
            listeEleves.setText(ancienneListe+"L'élève "+nomEleve+" "+prenomEleve+" a pour discipline.");
            boutonSupp.add(new JButton("Supprimer"));
            boutonSupp.get(i).setBounds(800, 100+y, 90, 20);
            boutonPhoto.add(new JButton(new ImageIcon("photo.jpg")));
            boutonPhoto.get(i).setBounds(100, 100+y, 20, 20);
            boutonSupp.get(i).addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JButton source = (JButton) evt.getSource();
                int posYBouton = (int) source.getLocation().getY();
                int posXBouton = (int) source.getLocation().getX();
                System.out.println(posYBouton);
                System.out.println(posXBouton);
                int numBouton = ((posYBouton - 100)/30); //premiere position a y = 100 et decalage de 30
                System.out.println(numBouton);
                if(posXBouton == 800){//position des boutons supprimés
                    buttonSuppEleveActionPerformed(evt, numBouton);
                }
            }
        });
            boutonPhoto.get(i).addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JButton source = (JButton) evt.getSource();
                int posYBouton = (int) source.getLocation().getY();
                int posXBouton = (int) source.getLocation().getX();
                System.out.println(posYBouton);
                System.out.println(posXBouton);
                int numBouton = ((posYBouton - 100)/30); //premiere position a y = 100 et decalage de 30
                System.out.println(numBouton);
                if(posXBouton == 100){//position des photos de profil
                    buttonFicheEleveActionPerformed(evt, numBouton);
                }
   
            }
        });
            accueilEleves.add(boutonSupp.get(i));
            accueilEleves.add(boutonPhoto.get(i));
            listeEleves.append("\n\n");
            accueilEleves.repaint();
            accueilEleves.revalidate();
            y+=30;
        }
        panelEleves.add(accueilEleves);
        panelEleves.repaint();
        panelEleves.revalidate();
        jPanel1.add(panelEleves);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }//GEN-LAST:event_buttonElevesActionPerformed
    private void buttonSuppEleveActionPerformed(ActionEvent evt, int numBouton){
        System.out.println("Bouton supp"+numBouton);
    }

    private void buttonFicheEleveActionPerformed(ActionEvent evt, int numBouton){
        System.out.println("Bouton fiche"+numBouton);
        if(!"".equals(ecole.getEleves().size())){
            String nomEleveR = ecole.getEleves().get(numBouton).getNom();
            System.out.println("nom eleve: "+nomEleveR);
            rechercherEleve(nomEleveR);
        }
       
    }
    private void buttonEnseignantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEnseignantsActionPerformed
        jPanel1.removeAll();
        listeEnseignants.setText("");
        panelEnseignants.removeAll();
        listeEnseignants.setBorder(null);
        listeEnseignants.setBackground(new Color(0,0,0,0));
        listeEnseignants.setEditable(false);
        scroll.setOpaque(false);
        scroll.getViewport().setOpaque(false);
        scroll.setBorder(null);
        scroll.setViewportBorder(null);
        ArrayList <JButton> boutonSupp = new ArrayList<>() ;
        ArrayList <JButton> boutonPhoto = new ArrayList<>() ;
        int y = 0;
       
        for(int i = 0; i<ecole.getProfs().size(); i++){
            String ancienneListe = listeEnseignants.getText();
            String nomProf = ecole.getProfs().get(i).getNom();
            String prenomProf = ecole.getProfs().get(i).getPrenom();
            String discipline = ecole.getProfs().get(i).getDiscipline();          
            listeEnseignants.setText(ancienneListe+"Le professeur "+nomProf+" "+prenomProf+" a pour discipline "+discipline+".");
            boutonSupp.add(new JButton("Supprimer"));
            boutonSupp.get(i).setBounds(800, 100+y, 90, 20);
            boutonPhoto.add(new JButton(new ImageIcon("photo.jpg")));
            boutonPhoto.get(i).setBounds(100, 100+y, 20, 20);
            boutonSupp.get(i).addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JButton source = (JButton) evt.getSource();
                int posYBouton = (int) source.getLocation().getY();
                int posXBouton = (int) source.getLocation().getX();
                System.out.println(posYBouton);
                System.out.println(posXBouton);
                int numBouton = ((posYBouton - 100)/30); //premiere position a y = 100 et decalage de 30
                System.out.println(numBouton);
                if(posXBouton == 800){//position des boutons supprimés
                    buttonSuppEnseignantActionPerformed(evt, numBouton);
                }
            }
        });
            boutonPhoto.get(i).addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                JButton source = (JButton) evt.getSource();
                int posYBouton = (int) source.getLocation().getY();
                int posXBouton = (int) source.getLocation().getX();
                System.out.println(posYBouton);
                System.out.println(posXBouton);
                int numBouton = ((posYBouton - 100)/30); //premiere position a y = 100 et decalage de 30
                System.out.println(numBouton);
                if(posXBouton == 100){//position des photos de profil
                    buttonFicheEnseignantActionPerformed(evt, numBouton);
                }
   
            }
        });
            accueilEnseignants.add(boutonSupp.get(i));
            accueilEnseignants.add(boutonPhoto.get(i));
            listeEnseignants.append("\n\n");
            accueilEnseignants.repaint();
            accueilEnseignants.revalidate();
            y+=30;
        }
        panelEnseignants.add(accueilEnseignants);
        panelEnseignants.repaint();
        panelEnseignants.revalidate();
        jPanel1.add(panelEnseignants);
        jPanel1.repaint();
        jPanel1.revalidate();         // TODO add your handling code here:
    }//GEN-LAST:event_buttonEnseignantsActionPerformed

    private void buttonSuppEnseignantActionPerformed(ActionEvent evt, int numBouton){
        System.out.println("Bouton supp"+numBouton);
    }

    private void buttonFicheEnseignantActionPerformed(ActionEvent evt, int numBouton){
        System.out.println("Bouton fiche"+numBouton);
        if(!"".equals(ecole.getProfs().size())){
            String nomProfR = ecole.getProfs().get(numBouton).getNom();
            System.out.println("nom eleve: "+nomProfR);
            rechercherEnseignant(nomProfR);
        }
    }
    private void buttonDisciplinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisciplinesActionPerformed
        jPanel1.removeAll();
        panelDisciplines.removeAll();
        panelDisciplines.add(accueilDisciplines);
        panelDisciplines.repaint();
        panelDisciplines.revalidate();
        jPanel1.add(panelDisciplines);
        jPanel1.repaint();
        jPanel1.revalidate();       
    }//GEN-LAST:event_buttonDisciplinesActionPerformed

    private void menuEnseignantsMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuEnseignantsMenuSelected
        jPanel1.removeAll();
        listeEnseignants.setText("test");
        jPanel1.add(panelEnseignants);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_menuEnseignantsMenuSelected

    private void menuElevesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuElevesMenuSelected
        jPanel1.removeAll();
        panelEleves.removeAll();
        panelEleves.add(accueilEleves);
        panelEleves.repaint();
        panelEleves.revalidate();
        jPanel1.add(panelEleves);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_menuElevesMenuSelected

    private void menuAccueilMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuAccueilMenuSelected
        jPanel1.removeAll();
        panelEnseignants.removeAll();
        panelEnseignants.add(accueilEnseignants);
        panelEnseignants.repaint();
        panelEnseignants.revalidate();
        jPanel1.add(panelMenu);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_menuAccueilMenuSelected

    private void menuDisciplinesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuDisciplinesMenuSelected
        jPanel1.removeAll();
        panelDisciplines.removeAll();
        panelDisciplines.add(accueilDisciplines);
        panelDisciplines.repaint();
        panelDisciplines.revalidate();
        jPanel1.add(panelDisciplines);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_menuDisciplinesMenuSelected

    private void buttonRechercheEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRechercheEleveActionPerformed
        String nomEleve;
        nomEleve = fieldEleves.getText();
        System.out.println("Nom de l'élève recherche: "+nomEleve);
        rechercherEleve(nomEleve);
    }//GEN-LAST:event_buttonRechercheEleveActionPerformed

    private void rechercherEleve(String nomEleveR){
        boolean trouve = false;
        panelEleves.removeAll();
        ficheEleve.setBorder(null);
        ficheEleve.setBackground(new Color(0,0,0,0));
        ficheEleve.setEditable(false);
        scroll4.setOpaque(false);
        scroll4.getViewport().setOpaque(false);
        scroll4.setBorder(null);
        scroll4.setViewportBorder(null);
        for(int i = 0; i<ecole.getEleves().size(); i++){
            String nomEleve = ecole.getEleves().get(i).getNom();
            String prenomEleve = ecole.getEleves().get(i).getPrenom();      
            
            System.out.println(nomEleve);
            if(nomEleve.equals(nomEleveR) || prenomEleve.equals(nomEleveR)){
                ficheEleve.setText("L'élève "+nomEleve+" "+prenomEleve+" a pour discipline.");
                trouve = true;
            }          
        }
        if(trouve == false){
            ficheEleve.setText("L'élève "+nomEleveR+" n'a pas été trouvé");
                System.out.println("Eleve non trouvé");
        }
        panelEleves.add(rechercherEleve);
        panelEleves.repaint();
        panelEleves.revalidate();
        jPanel1.add(panelEleves);
        jPanel1.repaint();
        jPanel1.revalidate();
    }
    private void rechercherEnseignant(String nomEnseignant){
        boolean trouve = false;
        panelEnseignants.removeAll();
        ficheEnseignant.setBorder(null);
        ficheEnseignant.setBackground(new Color(0,0,0,0));
        ficheEnseignant.setEditable(false);
        scroll2.setOpaque(false);
        scroll2.getViewport().setOpaque(false);
        scroll2.setBorder(null);
        scroll2.setViewportBorder(null);
        for(int i = 0; i<ecole.getProfs().size(); i++){
            String nomProf = ecole.getProfs().get(i).getNom();
            String prenomProf = ecole.getProfs().get(i).getPrenom();
            String discipline = ecole.getProfs().get(i).getDiscipline();      
            
            System.out.println(nomProf);
            if(nomProf.equals(nomEnseignant) || prenomProf.equals(nomEnseignant)){
                ficheEnseignant.setText("Le professeur "+nomProf+" "+prenomProf+" a pour discipline "+discipline+".");
                trouve = true;
            }          
        }
        if(trouve == false){
            ficheEnseignant.setText("Le professeur n'a pas été trouvé");
                System.out.println("Prof non trouvé");
        }
        panelEnseignants.add(rechercherEnseignant);
        panelEnseignants.repaint();
        panelEnseignants.revalidate();
        jPanel1.add(panelEnseignants);
        jPanel1.repaint();
        jPanel1.revalidate();        
    }
    private void buttonRechercheEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRechercheEnseignantActionPerformed
        String nomEnseignant;
        boolean trouve = false;
        nomEnseignant = fieldEnseignants.getText();
        fieldEnseignants.setText("");
        System.out.println("Nom de l'enseignant recherche: "+nomEnseignant);

    }//GEN-LAST:event_buttonRechercheEnseignantActionPerformed

    private void buttonAjoutEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjoutEleveActionPerformed
        panelEleves.removeAll();
        panelEleves.add(ajouterEleve);
        panelEleves.repaint();
        panelEleves.revalidate();
        boxClasse.addItem("Selectionner la classe");
        for(int i = 0; i<ecole.getClasses().size(); i++){
            String c = ecole.getClasses().get(i).getNom();
            boxClasse.addItem(c);
        }   
    }//GEN-LAST:event_buttonAjoutEleveActionPerformed

    private void buttonAjoutDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjoutDisciplineActionPerformed
        panelDisciplines.removeAll();
        panelDisciplines.add(ajouterDiscipline);
        panelDisciplines.repaint();
        panelDisciplines.revalidate();
    }//GEN-LAST:event_buttonAjoutDisciplineActionPerformed

    private void buttonAjoutEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjoutEnseignantActionPerformed
        panelEnseignants.removeAll();
        panelEnseignants.add(ajouterEnseignant);
        panelEnseignants.repaint();
        panelEnseignants.revalidate();
    }//GEN-LAST:event_buttonAjoutEnseignantActionPerformed

    private void boxClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxClasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxClasseActionPerformed

    private void buttonValiderEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderEleveActionPerformed
        String nomEleve, prenomEleve, classeEleve;
        nomEleve = fieldNomEleve.getText();
        prenomEleve = fieldPrenomEleve.getText();
        classeEleve = boxClasse.getSelectedItem().toString();
        if(!"".equals(nomEleve)&& !"".equals(prenomEleve) && !"Selectionner la classe".equals(classeEleve)){
            System.out.println(nomEleve+prenomEleve+classeEleve);
            fieldNomEleve.setText("");
            fieldPrenomEleve.setText("");
            boxClasse.setSelectedItem("Selectionner la classe");
            System.out.println(nomEleve+prenomEleve+classeEleve);
        }
        else{
            //JOptionPane.showMessageDialog(this,"Erreur",JOptionPane.ERROR_MESSAGE);
            System.out.println("Veuillez remplir tous les champs !");
        }
           
        
    }//GEN-LAST:event_buttonValiderEleveActionPerformed

    private void buttonValiderEnseignantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderEnseignantActionPerformed
        String nomEnseignant, prenomEnseignant, disciplineEnseignant;
        nomEnseignant = fieldNomEnseignant.getText();
        prenomEnseignant = fieldPrenomEnseignant.getText();
        disciplineEnseignant= fieldDisciplineEnseignant.getText();
        if(!"".equals(nomEnseignant) && !"".equals(prenomEnseignant) && !"".equals(disciplineEnseignant)){
            System.out.println("nom: "+nomEnseignant+" prenom: "+prenomEnseignant);
            fieldNomEnseignant.setText("");
            fieldPrenomEnseignant.setText("");
            fieldDisciplineEnseignant.setText("");
        }
        else{
            //JOptionPane.showMessageDialog(this,"Erreur",JOptionPane.ERROR_MESSAGE);
            System.out.println("Veuillez remplir tous les champs !");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_buttonValiderEnseignantActionPerformed

    private void buttonValiderDisciplineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderDisciplineActionPerformed
        String discipline;
        discipline = fieldDiscipline.getText();
        if(!"".equals(discipline)){
            System.out.println(discipline);
            fieldDiscipline.setText("");
        }
        else{
            //JOptionPane.showMessageDialog(this,"Erreur",JOptionPane.ERROR_MESSAGE);
            System.out.println("Veuillez remplir la discipline !");
        }         
            
    }//GEN-LAST:event_buttonValiderDisciplineActionPerformed

    private void buttonValiderNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderNiveauActionPerformed
        String niveau;
        niveau = fieldNiveau.getText();
        if(!"".equals(niveau)){
            System.out.println(niveau);
            fieldNiveau.setText("");
        }
        else{
            //JOptionPane.showMessageDialog(this,"Erreur",JOptionPane.ERROR_MESSAGE);
            System.out.println("Veuillez remplir le niveau !");
        } 
    }//GEN-LAST:event_buttonValiderNiveauActionPerformed

    private void buttonAjoutNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjoutNiveauActionPerformed
        panelNiveau.removeAll();
        panelNiveau.add(ajouterNiveau);
        panelNiveau.repaint();
        panelNiveau.revalidate();
    }//GEN-LAST:event_buttonAjoutNiveauActionPerformed

    private void buttonNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNiveauActionPerformed
        jPanel1.removeAll();
        panelNiveau.removeAll();
        panelNiveau.add(accueilNiveau);
        panelNiveau.repaint();
        panelNiveau.revalidate();
        jPanel1.add(panelNiveau);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }//GEN-LAST:event_buttonNiveauActionPerformed

    private void buttonClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonClassesActionPerformed
        jPanel1.removeAll();
        panelClasses.removeAll();
        panelClasses.add(accueilClasses);
        panelClasses.repaint();
        panelClasses.revalidate();
        jPanel1.add(panelClasses);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_buttonClassesActionPerformed

    private void buttonAjoutClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAjoutClasseActionPerformed
        panelClasses.removeAll();
        panelClasses.add(ajouterClasse);
        panelClasses.repaint();
        panelClasses.revalidate();
        boxNiveau.addItem("Selectionner le niveau");
        for(int i = 0; i<ecole.getClasses().size(); i++){
            String c = ecole.getClasses().get(i).getNom();//à changer avec le nom du niveau
            boxNiveau.addItem(c);
        }
    }//GEN-LAST:event_buttonAjoutClasseActionPerformed

    private void buttonValiderClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonValiderClasseActionPerformed
        String nomClasse, nomNiveau, anneeScolaire;
        nomClasse = fieldNomClasse.getText();
        anneeScolaire = fieldAnneeScolaire.getText();
        nomNiveau = boxNiveau.getSelectedItem().toString();
        if(!"".equals(nomClasse)&& !"".equals(anneeScolaire) && !"Selectionner le niveau".equals(nomNiveau)){
            System.out.println(nomClasse+nomNiveau+anneeScolaire);
            fieldNomClasse.setText("");
            fieldAnneeScolaire.setText("");
            boxNiveau.setSelectedItem("Selectionner le niveau");
        }
        else{
            //JOptionPane.showMessageDialog(this,"Erreur",JOptionPane.ERROR_MESSAGE);
            System.out.println("Veuillez remplir tous les champs !");
        }


    }//GEN-LAST:event_buttonValiderClasseActionPerformed

    private void boxNiveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNiveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNiveauActionPerformed

    private void fieldElevesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldElevesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldElevesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try{
            EcoleDAO ecoleDao = new EcoleDAO();
            ecole = ecoleDao.init();
        //    Ecole e = ecoleDao.find(1);
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Affichage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Affichage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accueilClasses;
    private javax.swing.JPanel accueilDisciplines;
    private javax.swing.JPanel accueilEleves;
    private javax.swing.JPanel accueilEnseignants;
    private javax.swing.JPanel accueilNiveau;
    private javax.swing.JPanel ajouterClasse;
    private javax.swing.JPanel ajouterDiscipline;
    private javax.swing.JPanel ajouterEleve;
    private javax.swing.JPanel ajouterEnseignant;
    private javax.swing.JPanel ajouterNiveau;
    private javax.swing.JComboBox<String> boxClasse;
    private javax.swing.JComboBox<String> boxNiveau;
    private javax.swing.JButton buttonAjoutClasse;
    private javax.swing.JButton buttonAjoutDiscipline;
    private javax.swing.JButton buttonAjoutEleve;
    private javax.swing.JButton buttonAjoutEnseignant;
    private javax.swing.JButton buttonAjoutNiveau;
    private javax.swing.JButton buttonClasses;
    private javax.swing.JButton buttonDisciplines;
    private javax.swing.JButton buttonEleves;
    private javax.swing.JButton buttonEnseignants;
    private javax.swing.JButton buttonNiveau;
    private javax.swing.JButton buttonRechercheEleve;
    private javax.swing.JButton buttonRechercheEnseignant;
    private javax.swing.JButton buttonValiderClasse;
    private javax.swing.JButton buttonValiderDiscipline;
    private javax.swing.JButton buttonValiderEleve;
    private javax.swing.JButton buttonValiderEnseignant;
    private javax.swing.JButton buttonValiderNiveau;
    private javax.swing.JTextArea ficheEleve;
    private javax.swing.JTextArea ficheEnseignant;
    private javax.swing.JTextField fieldAnneeScolaire;
    private javax.swing.JTextField fieldDiscipline;
    private javax.swing.JTextField fieldDisciplineEnseignant;
    private javax.swing.JTextField fieldEleves;
    private javax.swing.JTextField fieldEnseignants;
    private javax.swing.JTextField fieldNiveau;
    private javax.swing.JTextField fieldNomClasse;
    private javax.swing.JTextField fieldNomEleve;
    private javax.swing.JTextField fieldNomEnseignant;
    private javax.swing.JTextField fieldPrenomEleve;
    private javax.swing.JTextField fieldPrenomEnseignant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea listeEleves;
    private javax.swing.JTextArea listeEnseignants;
    private javax.swing.JMenu menuAccueil;
    private javax.swing.JMenu menuDisciplines;
    private javax.swing.JMenu menuEleves;
    private javax.swing.JMenu menuEnseignants;
    private javax.swing.JPanel panelClasses;
    private javax.swing.JPanel panelDisciplines;
    private javax.swing.JPanel panelEleves;
    private javax.swing.JPanel panelEnseignants;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelNiveau;
    private javax.swing.JPanel rechercherEleve;
    private javax.swing.JPanel rechercherEnseignant;
    private javax.swing.JPanel reportDisciplines;
    private javax.swing.JPanel reportEleves;
    private javax.swing.JPanel reportEnseignants;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JScrollPane scroll3;
    private javax.swing.JScrollPane scroll4;
    // End of variables declaration//GEN-END:variables
}
